### ISSUE TITLE
Write better READMEs

### ISSUE THREAD

**Issue by AlpriElse** [CS196Illinois/distributed-web#3]
Include Setup and Usage instructions in README

**Comment by AlpriElse** [comment]
Here is a Markdown Cheatsheet: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by warut-vijit** [comment]
Also generate dependencies with [pipreqs](https://pypi.python.org/pypi/pipreqs). It generates a file `requirements.txt`. Then to install dependencies, run `pip install -r requirements.txt`.

README files should have a *setup*, *usage*, and *features* section where someone entirely unfamiliar with your work can install dependencies and run your code
